let ramNames = [
    "S Amin",
    "M Anderson",
    "N R Ashireddy",
    "C Austin",
    "D Barela",
    "J Barth",
    "D Bilbao",
    "A Book",
    "M Boyle",
    "J Bunnell",
    "C Burks",
    "D Butkus",
    "C Carlson",
    "M Carrigan",
    "J Corrado",
    "D Davis",
    "B Eberle",
    "J Etl",
    "T Ewing",
    "D Eyre",
    "N Farhat",
    "A Fiel",
    "E Fitzpatrick",
    "J Garcia",
    "Y Gebremedhin",
    "K Gonzalez",
    "K Griem",
    "A Grudt",
    "I Haas",
    "C Hart",
    "S Houlton",
    "M Jackson",
    "C Jiang",
    "E Johnson",
    "D Kar",
    "S Kennell",
    "R Kughn",
    "M Lacrete",
    "J Lamfers",
    "H Lingle",
    "Z Liu",
    "T Lujan",
    "A Martinez",
    "A Matin",
    "C McCumber",
    "J Melvin",
    "M Messina",
    "M Mihevc",
    "A Mims",
    "M Moreno",
    "D Neumann",
    "T Nguyen",
    "M Nieberger",
    "C Petty",
    "J Quirk",
    "J Schmidt",
    "F Sizer",
    "R Steele",
    "G Vigil",
    "W Wallace",
    "A Walls",
    "C Wang",
    "X Wang",
    "M Warushavithana",
    "M Whitehead",
    "A Wilson",
    "Y Xu",
    "J Yang",

    "Bellatrix",
    "Netherspike",
    "Lizard",
    "Leander",
    "Phaser",
    "Falazure",
    "Brokenfang",
    "Raisin",
    "Hecate",
    "Harry",
    "Snape",
    "Miasma",
    "Shimmer",
    "Grassclaw",
    "MrCuddles",
    "Ambiance",
    "Chupathingy",
    "DoubleVision",
    "Acheron",
    "CaptainSmile",
    "Chimichanga",
    "Fume",
    "Loki",
    "Feathermoon",
    "Absinthe",
    "Nereus",
    "Cyanide",
    "Ellegon",
    "Slicer",
    "Spyro",
    "DoubleTrouble",
    "Zipactonal",
    "TipTap",
    "Grassclaw",
    "Snuggles",
    "IllBiteU",
    "Ancalagon",
    "Elpis",
    "Feathermoon",
    "Carboniferous",
    "Bloodmaw",
    "Namacuix",
    "Drakoth",
    "Dementionisa",
    "Aura",
    "Knuckle",
    "MagicShroom",
    "Mothball",
    "Polyporus",
    "GlowStick",
    "Zothogth",
    "Luminati",
    "ShotSathothu",
    "Russula",
    "SeanOfTheDead",
    "Tigger",
    "Hugs",
    "Blink",
    "Gemini",
    "Viral",
    "Ambiance",
    "Severjaw",
    "Ripmaw",
    "Cthulhu",
    "Herakles",
    "Orestes",
    "Astilabor",
    "Toltecatl",
    "Blinky",
    "Adrasteia",
    "Fleck",
    "Arsenic",
    "Sunshine",
    "Seaspray",
    "Rishul",
    "Skitz",
    "Runzel",
    "Adonis",
    "Gelure",
    "Kahaera",
    "Teicuih",
    "BettyBoop",
    "Aura",
    "Monarch",
    "Dawn",
    "Floater",
    "Nana",
    "Arngrimr",
    "Flopsy",
    "Wiggles",
    "Predator",
    "OmNomNom",
    "Lizardbreath",
    "Gelure",
    "Aasterinian",
    "Brokenfang",
    "Cambrian",
    "Glaucus",
    "Peekaboo",
    "Ricochet",
    "Popeye",
    "Claw",
    "Mutalisk",
    "Jumeaux",
    "Silurian",
    "Smaug",
    "PrplPeplEter",
    "Deimos",
    "Flash",
    "Runningsoul",
    "Big Bopper",
    "Vanish",
    "Quickfang",
    "Manitou",
    "Chubaka",
    "Powderpuffer",
    "Pickle",
    "Flygon",
    "Jasmine",
    "ShadowDancer",
    "Boss Hogg",
    "Man-o-War",
    "Dr Donut",
    "Charlie",
    "Grumpy",
    "Happy",
    "Sleepy",
    "Dopey",
    "Doc",
    "Bashful",
    "Sneezy",
    "Kirk",
    "Spock",
    "McCoy",
    "Scotty",
    "Uhuru"


];

export default ramNames;